version: '3.9'
services:
  postgres:
    image: 'postgres:12.14-alpine'
    volumes:
      - "postgres_volume:/var/lib/postgresql/data"
    ports:
      - '5432:5432'
    env_file:
      - './.env'
volumes:
  postgres_volume: